### ISSUE TITLE
Feature request: Sky/fog colormaps

### ISSUE THREAD

**Issue by nx-lilywawa** [MehVahdJukaar/polytone#10]
The current solution works well but there are 53 different Overworld biomes and I don't have the stamina to set individual colors for all of them

**Comment by MehVahdJukaar** [comment]
yeah im working on it. For now i have made so you can target multiple biomes with same jsons so at least there's that

**Comment by MehVahdJukaar** [comment]
also speaking of these I'm not exactly sure how to call their folder or how to structure them. BIome effects would take priority like they dowith grass color and these are not a per biome thing. they wouldbe a per dimension global clolormap just like lightmaps. Could make a single folder for lightmaps sky and fog but that could be confusing. could also make 2 folders 1 alled fogmaps or fogs (other folders are plural, this feels weird tho) and sky_colors

**Comment by kakashi1464** [comment]
I think this issue can be closed as resolved
