### ISSUE TITLE
Plw

### ISSUE THREAD

**Issue by LevKri2019** [MehVahdJukaar/polytone#100]
Hello, I can't create particles that go in a spiral, I want to repeat one effect so that particles come out of the fire block help me write the code
videos there are examples 
https://drive.google.com/file/d/1EyZDGcIa2wOqT7wbX43XrHN2sThiymP1/view?usp=sharing

https://drive.google.com/file/d/1RAFqw2fuG7zPvxgIc-sWowIxtAUpS4la/view?usp=sharing

**Comment by MehVahdJukaar** [comment]
Neat effect. Those looks cool to me. Why do you want to change them?

**Comment by LevKri2019** [comment]
No, you didn't understand, I want to repeat this effect, but I don't know how to write code for this effect, could you help me with writing code for this effect

**Comment by LevKri2019** [comment]
this effect is in a resource pack that has not been released yet

**Comment by MehVahdJukaar** [comment]
Did you even try? Just follow the wiki, I spent a lot of time writing that and asking without having tried expecting me to do it for you it's not very nice you know.
