### ISSUE TITLE
Version 1.21-2.5.1 Fabric Crashing

### ISSUE THREAD

**Issue by Quetzalis** [MehVahdJukaar/polytone#103]
The game crashed whilst initializing game
Error: java.lang.RuntimeException: Could not execute entrypoint stage 'client' due to errors, provided by 'polytone' at 'net.mehvahdjukaar.polytone.fabric.PolytoneFabric'!
Exit Code = -1

Also tested with minimal mods - only fabric api and polytone.

**Comment by UltimatChamp** [comment]
Can confirm on a new instance, here's the log: https://mclo.gs/842rnbG

**Comment by VOLKOUL** [comment]
Same on NeoForge 1.21.1

**Comment by Quetzalis** [comment]
Hotfix release 1.21-2.5.2 has fixed this :).
