### ISSUE TITLE
Particle's sound_emitter is not able to play custom sounds

### ISSUE THREAD

**Issue by Firch** [MehVahdJukaar/polytone#107]
Upon making a custom particle that emits a custom sound (which is registered with .csv and is included in .json), it isn't produced in any form (no sound, no subtitle, no visible sound amount increase in the F3 menu).

Assigning a vanilla sound instead of a custom one to custom particle plays the sound properly.

Possible errors that I considered:
- The sound is in proper format (it being .ogg)
- The sound is properly regirested (sound_events.csv, sounds.json include the sound)
- The sound is heard in game by other means (/playsound is audible and the subtitles are visible when using it)
- The sound cannot be played because of the stereo format (putting a vanilla stereo sound works properly)

**Comment by MR-CHOO** [comment]
Went through your files, not a bug, it was a typo.
