### ISSUE TITLE
problem with codding

### ISSUE THREAD

**Issue by LevKri2019** [MehVahdJukaar/polytone#112]
please help me how to make the colormap of the block work only in certain biomes, the screenshot shows the foliage of a dark oak tree not in a dark forest, it is the same color as in a dark forest, I want it to be just green ,here is my code {
    "targets": ["minecraft:dark_oak_leaves"],
    "colormap": {
       "y_axis": "0",
       "x_axis": "0"
![image](https://github.com/user-attachments/assets/864a3167-adb9-4d07-a0f1-577a0389e5bb)

**Comment by MehVahdJukaar** [comment]
you can use the grid prre made colormap type or the "biome_id" as a sampler for one of the axis. This in short but you should read more about it on the wiki. Also read about the biome_id_mapper

**Comment by LevKri2019** [comment]
english is not my native language, so it's difficult for me to find some terms in the wiki, I've gone through the entire wiki, reread biome mapper id biome id many times, but still I can't do anything, could you give me a simple example when a block in one biome with a texture of one color and in another biome of another color

**Comment by LevKri2019** [comment]
but by the way, I managed to master the creation of particles and I learned how to paint textures, but they are painted the same in all biomes (and I mastered the fog color of the sky

**Comment by MehVahdJukaar** [comment]
the sample pack should have one of those. start from that, do it step by step changing 1 thing at time so you know sutff is woking.
