### ISSUE TITLE
problem with fo fade 

### ISSUE THREAD

**Issue by LevKri2019** [MehVahdJukaar/polytone#113]
I do not understand how the fog fade parameter works, I added it to the json files of both biomes that can be seen in the video, that is, in plains and sprase jungle, I changed different values, but it did not have any effect. I understand that this parameter is responsible just for the smooth transition between different skies and foggy, but I could not understand how to make it work
https://drive.google.com/file/d/1bcJ6bCLsWN-BKg_-Ch2sSUJANEnW6wgx/view?usp=sharing

**Comment by MehVahdJukaar** [comment]
fog fade is a parameter that scales the distance between the fog start plane and the for end plane (rom 0% fog to 100% fog). the other parameter just scales one of the planes

**Comment by LevKri2019** [comment]
can i somehow make a softer transition between different fog in different biomes

**Comment by MehVahdJukaar** [comment]
yes thats what that's for. 
one parameter scales the distance between 100% for and no fog and the other moves how far away the fog starts. This is per biome so you can tweak those ididivually

**Comment by LevKri2019** [comment]
thanks u've helped me for real
