### ISSUE TITLE
Dual tone grass

### ISSUE THREAD

**Issue by LevKri2019** [MehVahdJukaar/polytone#114]
hi, I have a problem, I don't understand how to make a double tone for biomes, I need to use a colormap if so, please
![Uploading Screenshot_4.png…]()

**Comment by MehVahdJukaar** [comment]
Hm that image you sent doesn't load

**Comment by MehVahdJukaar** [comment]
Idk what you mean by double tone but if you mean you want to have part of your block model use some colour and some other use some other colour you can do so by giving each face a different tint index in the model. Then add a compound colormap to the block. See end of colormap section in blocks modifiers

**Comment by LevKri2019** [comment]
![Screenshot_4](https://github.com/user-attachments/assets/c17febfd-2d15-4088-ba7f-c6006e731e96)

**Comment by LevKri2019** [comment]
here is an example

**Comment by LevKri2019** [comment]
I'll read it well

**Comment by MehVahdJukaar** [comment]
Where's that from?

**Comment by MehVahdJukaar** [comment]
If what you want to do si have variations you can use noise. Read about that topic there on wiki and use it to offset some of the sampling on colormaps. There isn't one way to do it, can be done in a million diff ways
