### ISSUE TITLE
game_time repeats daily instead of every 30 days

### ISSUE THREAD

**Issue by Shrimpsnail** [MehVahdJukaar/polytone#118]
game_time mentioned in the wiki as [lasting 0-29 days](https://github.com/MehVahdJukaar/polytone/wiki/Variant-Textures#weather-and-day-time-animated-textures), instead does a full cycle everyday, identical to day_time.

Purely as a suggestion the ability to change the period or making it larger by default

**Also add season mod variable**

Example:

stone.png.mcmeta:
```json
{
  "animation": {
    "interpolate": false,
    "mode": "day_time"
  }
}
```
oak_planks.png.mcmeta:
```json
{
  "animation": {
    "interpolate": false,
    "mode": "game_time"
  }
}
```
results:
![2024-12-06_20 56 38](https://github.com/user-attachments/assets/9d610417-771e-445d-b2be-b24e34245a38)
![2024-12-06_20 56 40](https://github.com/user-attachments/assets/170a7806-fd88-4cbe-b869-beb1c8b1a229)
![2024-12-06_20 56 42](https://github.com/user-attachments/assets/f5e3fdfe-8027-4fff-a232-5194ecb7e15d)

![2024-12-06_20 56 44](https://github.com/user-attachments/assets/df6cb0b3-f979-4ce5-837e-3939814fd84b)

**Comment by MehVahdJukaar** [comment]
wiki is incorrect. first gametime variable is indeed using day time. however to change thecycle duration you need to use "time_cycle_duration" and set whichever numer you want
