### ISSUE TITLE
Incompatibility with 1.21.4+

### ISSUE THREAD

**Issue by leeineian** [MehVahdJukaar/polytone#119]
Take your time.

**Comment by MehVahdJukaar** [comment]
Then why is this here if not to out pressure 💀
It's obvious it's not compatible 1.21.4 is a big version jump and I don't think I have files marked for 1.21.4

**Comment by leeineian** [comment]
Was just reminding sorry 😟

**Comment by leeineian** [comment]
Thank youuu dev 🙇
