### ISSUE TITLE
[FORGE] grass_color not working for swamp biome

### ISSUE THREAD

**Issue by NeonCranberries** [MehVahdJukaar/polytone#12]
I'm trying to change the swamp biome values and everything seems to be working except for the grass_color

{

    "sky_color": 4325376,
    "fog_color": 9913412,
    "water_color": 2239033,
    "water_fog_color": 2894401,
    "grass_color": 4539717,
    "foliage_color": 1719582,
    "particle": {
      "options": {
         "type": "minecraft:ash"
      },
      "probability": 0.2
     }
}

![2024-01-20_12 04 45](https://github.com/MehVahdJukaar/polytone/assets/146756418/c25a48b5-cc73-4e39-bead-a05646b65f7f)

I do realize the swamp is special in how it has two different grass colors but am unsure how I would account for that for this to work.

**Comment by MehVahdJukaar** [comment]
hm I'll look into it

**Comment by MehVahdJukaar** [comment]
so the game works like this:
if biome has special biome effect it gets those. if not it gets the colormap grass color
THEN if biome has some extra biome color effect function (just swamp has that), it uses that to transform the color calculated above. I'm not sure what  i should do here. EIther nuke the special effect function when a new color is applied or allow one to customize that with a math function

**Comment by MehVahdJukaar** [comment]
oh update, aparently it already is customizable. you need to add "grass_color_modifier" with one of these values 
![image](https://github.com/MehVahdJukaar/polytone/assets/24719182/e34be185-6606-4e74-bc76-92ab20e65cd4)

**Comment by NeonCranberries** [comment]
Ahh that worked...Thank you! And sorry to bother you.
