### ISSUE TITLE
Polytone on 1.20.4 lack the translucency block modifier 

### ISSUE THREAD

**Issue by Reijvi** [MehVahdJukaar/polytone#127]
As the title says, I'm unsure of if other versions besides 1.20.4 have the same issue, but Polytone on 1.20.4 doesn't seem to support changing a blocks rendering via the block modifier. When using a resource pack like Reimagined, the translucent effects on blocks become solid.

Reimagined on Minecraft 1.21.3:
![bild](https://github.com/user-attachments/assets/df6176de-9bb7-465c-9547-3898da74cfa0)

Reimagined on Minecraft 1.20.4:
![bild](https://github.com/user-attachments/assets/44f9318a-9d0f-4e66-a585-d28703bcf60c)

**Comment by MehVahdJukaar** [comment]
oh yeah 1.20.4 is abandoned. i thought this was relevant in main 1.20 modding version 1.20.1.
I will soon port to 1.21.4 so "only" version i will maintain will be 1.20.1, 1.21.1 and 1.21.4 which are many already

**Comment by Reijvi** [comment]
Ah, I see, thanks for tellin' me though, very handy to know parity-wise.
