### ISSUE TITLE
strange error warning with new version

### ISSUE THREAD

**Issue by shinycolororange** [MehVahdJukaar/polytone#128]
fabric 1.21.1, the new 3.0 version gives me this (see txt) warning when entering a world
[error.txt](https://github.com/user-attachments/files/18174336/error.txt)
alex caves does not even exist for fabric so am not sure what poly is calling there

**Comment by MehVahdJukaar** [comment]
It's failing as the same as a tag with that entry would fail. The wiki explains that if you want to have an entry for a mod that might not be there you either add a condition on the JSON or make the target entry optional. Previous version was bugged where it did not throw this error
