### ISSUE TITLE
Suggestion: Seasons Implementation

### ISSUE THREAD

**Issue by Flumplin** [MehVahdJukaar/polytone#13]
Not sure if this fits the scope of the mod, but being able to manually config both colors and textures for seasons mods is seemingly absent from extant offerings.  It would be a big help for adding compatibility/improvements.  Great mod btw, really appreciate you making these utilities available and easy to work with ^^

**Comment by MehVahdJukaar** [comment]
Such customisation is what season mods should give you by themselves. There's no seasons in the game and surely it isn't this mod duty to add configuration for other mods because they are too lazy to add them themselves
