### ISSUE TITLE
1.21.4 Crash on Startup

### ISSUE THREAD

**Issue by NiuhiPlays** [MehVahdJukaar/polytone#131]
At first I thought it was a compatiblity issue, but after a clean 1.21.4 install with just the Fabric API 0.112.1 and Polytone 1.21.4-3.10 it still produces this error.

[polytone error.txt](https://github.com/user-attachments/files/18189217/polytone.error.txt)

**Comment by Danny404Error** [comment]
[crash.txt](https://github.com/user-attachments/files/18194973/crash.txt)

Happened to me as well, I had updated polytone and was launching minecraft when it crashed on me. I thought that maybe, based off the crash, it was a mod conflict between debugify/polytone, but I remembered that they worked together before, so I decided to downgrade and sure enough, it launched.

**Comment by MehVahdJukaar** [comment]
Are you sure you are using latest mod version? Should be 3.1.1

**Comment by NiuhiPlays** [comment]
Using 3.1.2 it starts up without any trouble! The Modrinth App didn't include the newer versions, and is stuck on 3.1.0
