### ISSUE TITLE
Crashing linked to a mixin injection failure (Simply Optimised mod pack).

### ISSUE THREAD

**Issue by y4n2sTh3Cod3r** [MehVahdJukaar/polytone#136]
I believe that the issue is caused by a mixin (specifically polytone.mixins.json:AbstractionContainerScreenMixin) that tried to inject into the slotifyColor method and failed.

### Note
_**I did remove mods until it fixed the problem and I removed every mod in every combination. Every time removing polytone fixed it**_

I debugged it in my own eclipse environment to get stack traces and custom logs and that is how I pin pointed the issue.

However, I did realise that if I had looked harder at the log file (linked under) I would have found a reference to the specific mixin.
[latest.log](https://github.com/user-attachments/files/18247334/latest.log)

_**If anyone is willing to give me feedback I will gladly accept it.**_

**Comment by MehVahdJukaar** [comment]
so what was the issue?
