### ISSUE TITLE
colormap coordinates wrap around / offset in colormap coordinates(?)

### ISSUE THREAD

**Issue by mineland-2048** [MehVahdJukaar/polytone#139]
Having a colormap that goes from 0 to 1 overflows when it gets to 1. This didnt happen on older versions, and can be mitigated by doing a min([exp], 0.99), but its not desireable/

```json
 {
    "x_axis": "biome_id",
    "y_axis": "RAIN",
    "biome_id_mapper": "minecraft:overworld_weather"
 }
```

https://github.com/user-attachments/assets/f7cd5ebf-1649-42ea-8536-f97cfb8a1c97

It could also be some sort of coordinate offset aswell though due to previous testing. Specifically in the biome mapper, each biome had to be offset by 1 pixel (texture size 256) and it could be something similar here, but its probably not that. The texture wrap could be useful in some cases, but having 1 be a wraparound seems a bit unintentional.

Ill attach a resource pack affected by this (> `assets/minecraft/polytone/biome_id_mappers/overworld_weather.json` should start with 0 instead of 1) 
[bedrock-weather 2024-12-27@19.53.46.zip](https://github.com/user-attachments/files/18264647/bedrock-weather.2024-12-27%4019.53.46.zip)

**Comment by MehVahdJukaar** [comment]
Version? Thought I fixed this in last release but maybe not for all versions

**Comment by mineland-2048** [comment]
I tested on 3.1.5. Somehow I had updated all my mods and polytone didnt. My bad, it works on 3.1.6 as intended
