### ISSUE TITLE
Crash when clicking Singleplayer button

### ISSUE THREAD

**Issue by Uranite** [MehVahdJukaar/polytone#17]
Possible mod conflict with sodium, this doesn't happen without sodium
Happens on minecraft 1.20.4, this doesn't happen on 1.20.1
Mod loader: Fabric with fabric loader 0.15.6
Crash log:
https://mclo.gs/NoNJtaS
To reproduce:
1. Install polytone, fabric API, and sodium
2. Launch the game and click on the Singleplayer button

**Comment by MehVahdJukaar** [comment]
does this happen with latest version?

**Comment by Uranite** [comment]
> does this happen with latest version?

nope 👍
