### ISSUE TITLE
Crashes on forge 1.20.4

### ISSUE THREAD

**Issue by nickademas** [MehVahdJukaar/polytone#18]
[latest.log](https://github.com/MehVahdJukaar/polytone/files/14213115/latest.log)
polytone 1.20.4-1.14.3

**Comment by MehVahdJukaar** [comment]
Forge Is not supported. None of the files are marked for it. Use neoforge

**Comment by nickademas** [comment]
![obraz](https://github.com/MehVahdJukaar/polytone/assets/46594867/8d68f889-5aca-4e7c-b39a-0b52c6f202b5)
they are marked for forge 1.20.4

**Comment by MehVahdJukaar** [comment]
Darn it modrinth

**Comment by MehVahdJukaar** [comment]
fixed. Btw if you find any 1.20.4 file marked for forge for any mod really, its most likely an oversight
