### ISSUE TITLE
Crash on Fabric 1.20.1 with Golden days texture pack

### ISSUE THREAD

**Issue by Dr01000111** [MehVahdJukaar/polytone#20]
When opening the single player menu with the golden days texture pack applied the game crashes

The Crash Log

https://mclo.gs/kX2a99y

I am using V60 of the Abyssalcraft mod pack on modrinth as I was trying to add Polytone and this crash only happens when there are no saves.

**Comment by MehVahdJukaar** [comment]
Are you using latest version?

**Comment by Dr01000111** [comment]
I am using the latest version of polytone.

**Comment by Dr01000111** [comment]
never mind the release yesterday fixed the issue
