### ISSUE TITLE
Question: falling_dust

### ISSUE THREAD

**Issue by Thornecrous** [MehVahdJukaar/polytone#23]
Hello! I am currently trying to make a texturepack on the basis of Polytone. Right now i'm stuck on implementing sand particle into the desert's ambience. I read the wiki and assembled the json file. I discovered that falling_dust particle is based on the block that it falls from, so in that case, i need a sand one. i looked up the id on the minecraft wiki, i downloaded several datapacks that use that same particle and copied it from there, it just doesn't work. I tried everything i knew. (All other particles work as intended, but not the falling_dust.)
So i came here to ask a question: is falling_dust supported by the mod, and if it is, what is the synthax for it?

**Comment by MehVahdJukaar** [comment]
thing is there is a falling dust particle but its not unique to sand. you could change its color but it will change it for all other ones that are not from a sand block. Might look at ways to target that specific one

**Comment by Thornecrous** [comment]
i will probably need the red sand one in the future too, so it would be lovely

**Comment by MehVahdJukaar** [comment]
done

**Comment by Thornecrous** [comment]
Thank you very much!
How would you target it though?
something like: "minecraft:falling_dust minecraft:sand"?
