### ISSUE TITLE
[FABRIC] Resource pack overlap renders incorrectly with Polytone

### ISSUE THREAD

**Issue by BlueJayofEvil** [MehVahdJukaar/polytone#26]
Minecraft: 1.20.4
Fabric Loader: 0.15.7
Fabric API: 0.96.11
Polytone: 1.14.6

I normally use VanillaTweaks' redstone power levels in addition to other resource packs without issue. But for some reason if I enable Polytone it renders incorrectly.
I've tested this with a minimal set up to avoid any other mods or resource packs possibly interfering.
For this test I'm using VanillaTweaks' redstone power levels (https://vanillatweaks.net/picker/resource-packs/) and RGBstone by TheDarkCoder (https://www.planetminecraft.com/texture-pack/rgbstone-5638971/)

Here's the resource pack order for demonstration:
![2024-03-21_22 58 59](https://github.com/MehVahdJukaar/polytone/assets/1016034/3d6047dc-e395-4538-bb22-5bb9d447f42d)

Here's how it looks normally without Polytone:
![2024-03-21_22 56 07](https://github.com/MehVahdJukaar/polytone/assets/1016034/e00583c3-ccf0-4289-aa33-cd798d2de530)
![2024-03-21_23 45 19](https://github.com/MehVahdJukaar/polytone/assets/1016034/fd76a8ca-4174-4a4c-8aa9-c3d8b7531805)

Here's how it looks when Polytone is enabled:
![2024-03-21_22 57 09](https://github.com/MehVahdJukaar/polytone/assets/1016034/77b83e21-5a99-4816-9d20-bf2c72df29b1)
![2024-03-21_23 44 12](https://github.com/MehVahdJukaar/polytone/assets/1016034/deb914f9-6e81-4565-b183-f1dfcce5c4ec)

Resource pack list for without overlapping packs for comparison demonstration:
![2024-03-21_22 59 33](https://github.com/MehVahdJukaar/polytone/assets/1016034/5e2bf30f-9196-4f82-b918-a5b20587c3d2)

How that looks with Polytone:
![2024-03-21_22 59 40](https://github.com/MehVahdJukaar/polytone/assets/1016034/fe9c9ba7-a87b-440a-b813-9aa193ef35dd)
(seems fine without overlapping resource packs)

I normally use a much larger modpack with tons of resource packs that overlap, but I've never had this specific issue until I tried Polytone. And what's weird is it seems to be the redstone dust specifically that seems to have the issue. I'm not aware of other textures that I've seen have this issue, but I have not tested everything to be sure. This was just the most glaring example I saw.

**Comment by MehVahdJukaar** [comment]
I see that rgb texture pack is not trying to modify the particle color to rgb despite the fact that polytone allows such a thing

Anyways you can have many overlapping packs but similar feature will overlap. Say you have 2 models in 2 packs for the same block. Obviously only 1 will take effect .

Anyways all seems to be working "fine" as far as I'm concerned. 
That rgb has addede a colormap (via optifine format) that goes from gray to white, replacing the red one that redstone dust have.
The second pack you have has a model with 2 quads (the number and its overlay). Both are white but just one is tinted by having the tintindex of 0. This means that that quad is colored with the colormap. Normally red. WHen rgb pack is on, since its new redstone wire colormap is now white, both appear white

**Comment by BlueJayofEvil** [comment]
> To add onto this i actually find the first image you sent to be the incorrect one.

I appear to have uploaded the wrong image. You ae correct.
I just tried again, with and without. Here's how that looks:

Without Polytone:
![2024-03-22_13 13 51](https://github.com/MehVahdJukaar/polytone/assets/1016034/74e9ac5e-dd79-4084-8540-23a87f993085)

With Polytone:
![2024-03-22_13 14 55](https://github.com/MehVahdJukaar/polytone/assets/1016034/bfb88b76-54ee-4bd6-b414-d6304e4e7375)

Your explanation makes sense given what I'm seeing. The brightness is cranked to the max when both packs are used in conjunction with Polytone, making the white texture just a bright splotch and the rest of the colors very bright and colorful.
I'll find a workaround if I really need to. This isn't a major issue for me, it just caught my attention with my normal modpack.
Thank you.

**Comment by MehVahdJukaar** [comment]
So to fix you have to make that number overlay from that overlay pack animated with a rainbox texture to match the RGB one. That way both packs will be properly integrated. You can also assign to the overlay a divverent tint index or make it black
