### ISSUE TITLE
latest polytone version for fabric seems to crash instatnly

### ISSUE THREAD

**Issue by fucksophie** [MehVahdJukaar/polytone#27]
The error is posted here: https://paste.md-5.net/nejanodame.sql
Version 1.20-1.16.1 of the mod, fabric 1.20.4, fabric loader 0.16.7 and fabric api 0.91.2-0.17.1

**Comment by MehVahdJukaar** [comment]
cant replicate. tested with latest fabric loader 0.15.7 and latest fabric api 0.96.11+1.20.4
Might be a conflict with another mod

**Comment by rilakuma123** [comment]
Could you share the latest.log from your logs folder? It'll have more information.

**Comment by MehVahdJukaar** [comment]
Won't be that useful. It's s mixing issue which can happen either because another mod used a redirect mixing or the game version is different (or core mods hackery but nobody uses those anymore)
Try on a new instance
