### ISSUE TITLE
Crashes on startup when BedrockIfy is present

### ISSUE THREAD

**Issue by andrwcrr** [MehVahdJukaar/polytone#29]
Crash happens on polytone version 1.20-1.17.2. Crash does not happen as late as polytone version 1.20-1.16.8.

**Comment by andrwcrr** [comment]
[latest.log](https://github.com/MehVahdJukaar/polytone/files/14836494/latest.log)

**Comment by andrwcrr** [comment]
[crash-2024-04-02_08.17.40-client.txt](https://github.com/MehVahdJukaar/polytone/files/14836497/crash-2024-04-02_08.17.40-client.txt) heres the crash report for good measure

**Comment by MehVahdJukaar** [comment]
Looking at that mod code, in terms of mixins, it's really bad full or redirects. See redirects are a thing that when used makes that specific thing you edit inherently incompatible with all other mods that touch it and should never be used really . Obviously their issue
https://github.com/search?q=repo%3Ajuancarloscp52%2FBedrockIfy%20redirect&type=code

**Comment by andrwcrr** [comment]
I see, ill close this one now
