### ISSUE TITLE
Incorrect information about water colormap on wiki.

### ISSUE THREAD

**Issue by ShadySalesGnome** [MehVahdJukaar/polytone#30]
The the incorrect information in question is this:
"Want to use colormap? You can already do that in vanilla for water"

Correct information:
in vanilla Minecraft water biome color cannot be changed, a water colormap was added in beta 1.6, however it was never used and was later removed.

Edit: Optifine does include a water colormap, which does allow you to edit or remove biome color for water entirely, this may be where the confusion originally came from, and why this feature isn't supported in Polytone.

**Comment by MehVahdJukaar** [comment]
true. Ill remove that line. Water color is howeve fully supported in polytone, both with that old optifine stuff and using biome modifiers aswell which is how vanilla handles water color. each biome has a color information associated. Polytone has fluid modifiers that can also change the color of any fluid not just water. Both those methods are preferred over legacy formats

**Comment by ShadySalesGnome** [comment]
I appreciate the clarification, I couldn't find anything for fabric to change biome water.
I'm going to go ahead and close the issue.

**Comment by MehVahdJukaar** [comment]
you sure you dont have sodium? that breask stuff. use embeddium fabric
