### ISSUE TITLE
Bug: Dark skies

### ISSUE THREAD

**Issue by Thornecrous** [MehVahdJukaar/polytone#31]
At random moments the sky in the biome im in becomes darker, like in the picture
![Безымянный](https://github.com/MehVahdJukaar/polytone/assets/163655176/92aa88b5-de80-44c1-ae8a-de1943dc359a)
It becomes normal when i go into a different biome, and darkens again when i go back

**Comment by MehVahdJukaar** [comment]
Are you in any particular biome when that happens?

**Comment by MehVahdJukaar** [comment]
Do you have any pack on?

**Comment by Thornecrous** [comment]
it happens in every biome, randomly
i use my own pack that changes the sky color in some biomes, but megataiga and river on the screen are not part of them

**Comment by Thornecrous** [comment]
i also use Fog looks good now, which makes the sky dark when you are in cave, but when i disable it the issue remains

**Comment by MehVahdJukaar** [comment]
Can you send your pack so I can test?

**Comment by Thornecrous** [comment]
1 minute

**Comment by Thornecrous** [comment]
[Polytone Skyline.zip](https://github.com/MehVahdJukaar/polytone/files/14893357/Polytone.Skyline.zip)

**Comment by MehVahdJukaar** [comment]
I tried flying around through diff biomes including river and couldnt replicate. Are you using other mods that might affect this?  Try without. Also double check the biome whenever that happens.

**Comment by Thornecrous** [comment]
i believe this happens not depending on the biome, i can remember seeing it in:
plains
cherry grove
river
megataiga
When i was testing the pack i sent, i saw it also in the jungle and mesa biomes, the pack was working, but the colors were darker and dimmer
As for the mods, the ones i can think of that caused the conflict (this doesn't mean i am right, i just got no clue what exactly they do, so maybe they are involved) are:
BadOptimisations
Concurrent Chunk Management Engine
Immediately Fast
Lithium
Satin
Sodium
All others are small additions like Zoomify or Wakes
I'll try to disable my mods, except for a few like Continuity and will play like that for a few days to report if the issue is still there

**Comment by Thornecrous** [comment]
i can remember the issue appeared shortly after i installed polytone, i didn't exist before
still, i am too deep to reject it
this mod is cool ah

**Comment by Thornecrous** [comment]
i shrunk my modlist to this
let's see if the game will even start now
![image](https://github.com/MehVahdJukaar/polytone/assets/163655176/c354781c-464e-416b-90e4-94854db61300)
testing begins

**Comment by Thornecrous** [comment]
ah yes, the crispy 8 fps
i noticed from all the mods i mentioned before CCME is in alpha right now, so, for now i gonna reinstall all of them except it

**Comment by Thornecrous** [comment]
i played without c2me for a day and a half, performance did a nosedive, but i haven't seen any dark skies yet
i am starting to suspect i am wasting your precious time here
gonna close this issue for now
