### ISSUE TITLE
Biome Effects foliage and grass colors don't work with Sodium

### ISSUE THREAD

**Issue by robinsmith7** [MehVahdJukaar/polytone#32]
... I got biome effects to work thanks for letting me know where I went wrong with that. Idk if you can change grass/foliage color within biome effects, it looks like you should be able to but I can't seem to do that...

_Originally posted by @ShadowMorde in https://github.com/MehVahdJukaar/polytone/issues/14#issuecomment-1920258017_
            
I unfortunately experience the same issue. I tested this only using Polytone and Sodium using the same resource pack. Without Sodium the colors change, with Sodium they do not. Fog and sky colors biome effects do work. I can also get the grass colors to change with a colormap on the grass_block.

Should be pretty straightforward to reproduce, but I can provide more details if necessary.

Thank you for your work.

**Comment by MehVahdJukaar** [comment]
Use embeddium fabric

**Comment by MehVahdJukaar** [comment]
If not report to sodium. It's clearly their issue as you have confirmed by disabling it

**Comment by robinsmith7** [comment]
Embeddium works, I'll use that. Thanks!
