### ISSUE TITLE
"Resource reload failed" error when trying to enable Reimagined RP

### ISSUE THREAD

**Issue by Ron1xeevich** [MehVahdJukaar/polytone#36]
### Environment

MultiMC launcher 0.7.0-3857
Minecraft 1.20.4
Fabric Loader 0.15.9
Fabric API 0.96.11
Polytone 1.18.5
[Reimagined RP](https://modrinth.com/resourcepack/reimagined/version/v1.45)

### Steps to reproduce

   1. Launch instance
   2. Click options
   3. Click resource packs
   4. Click arrow on Reimagined RP
   5. Apply changes

### Log
https://paste.ee/p/t4GIH

**Comment by MR-CHOO** [comment]
This is an issue with the reimagined pack, it needs to be fixed by the pack's developer.
