### ISSUE TITLE
No compatible

### ISSUE THREAD

**Issue by Ricotech11** [MehVahdJukaar/polytone#38]
Im currently using modrinth 1.20.5, The fulbright pack is compatible but says its made for an older version but it works, BUT the polytone isn't compatible with 1.20.5, what do I do?

![Screenshot 2024-04-24 153823](https://github.com/MehVahdJukaar/polytone/assets/161983688/681f01d9-cf69-40c6-82db-493431be182a)

**Comment by MehVahdJukaar** [comment]
use 1.20.6 version
