### ISSUE TITLE
Version 1.17.7 for MC 1.20.1 seems to prevent loading, no related log output

### ISSUE THREAD

**Issue by katubug** [MehVahdJukaar/polytone#39]
When I updated to one of the latest 2 versions of Polytone, my instance fully fails to load, and very early on. The log is incredibly unhelpful (to me anyway). Here's my latest.log: https://gist.github.com/katubug/22e4202743d5deca0d7bfcf984f394ac

This issue doesn't occur with Polytone 1.14.9, so I'll just avoid updating for now. Thanks for your time!

**Comment by katubug** [comment]
Unfortunately, that's all the info I have. I don't have a debug.log and I get no other errors or info. If I have time I can try a binary search to see if it's a mod conflict, but I'm not sure when that will be.

**Comment by MehVahdJukaar** [comment]
hm are you using a texture pack?
your log is a bit weird because it just ends randomly without throwing any error. Does it make a crash report?
Check without rendering mods or similar and bump your loader version if it isnt updated

**Comment by katubug** [comment]
Okay, here's what I've tried:

1. I updated from 47.2.20 to 47.2.30. 

2. Then I disabled Oculus and Embeddium (and other dependent mods like Embeddium Options, Embeddium Plus, Dynamic Lights for Embeddium).

3. Then I disabled random other mods:
- Entity Model/Texture Features
- Canary
- CIT Resewn
- Cull Less Leaves
- Euphoria Shaders Patcher
- Farsight
- Ferrite Core

3. Then I moved all my resourcepacks to an external folder.

Still the same result. Still nothing in the log and no crash report. Also, not as part of this troubleshooting process, I did remove Sinytra Connector and the one mod I was using with it, so that won't be the issue either.

Sorry, I wish I had anything to go on.

**Comment by MehVahdJukaar** [comment]
it should work on both but does changing to neoforge work?

**Comment by katubug** [comment]
I tried making a new profile for NeoForge and just copying the mods over and removing the ones which weren't NeoForge compatible, and that started up and I was able to enter a world.

The mods I deleted were:
- Caupona
- Night Config Fixes (duh)
- Hearth and Home
- Useful Slime
- Load My F***ing Tags

So I then disabled those mods from my main instance, but it still refuses to start. I re-enabled the mods.

I then went through and temporarily renamed my config, defaultconfig, kubejs, resourcepacks and shaderpacks folders, to see if the issue was some bit of customization I'd done. But it still refuses to start. It did generate new config and defaultconfig folders, if that helps narrow anything down. The kubejs, resourcepacks, and shaderpacks folders didn't get regenerated.

**Comment by MehVahdJukaar** [comment]
hm not sure really. must be that it didnt like forge? thats also odd because use old forge all the time in 1.20.1. Cant be a resource pack thing either if you remove the folder. ifonly log would say something more

**Comment by Reshirou** [comment]
This crash happens when having both Polytone and Moonlight loaded at the same time, for some reason.

Just Polytone? Load. Just Moonlight? Load. Both? Instant crash. Here is a pastebin of my Game Output since the latest.log apparently is no help. https://pastebin.com/jHcxzvEN

**Comment by MehVahdJukaar** [comment]
ok so no clue why but it requires neoforge. Luckily all those new versions are marked as neoforge

**Comment by MehVahdJukaar** [comment]
this is a very od issue that only happen with old forge but not neoforge. Use neoforge or try the new version i posted

**Comment by Reshirou** [comment]
1.17.7 crashes on Neoforge still too, but 1.17.13 works on both Forge and Neoforge just fine now

I think you can mark this fixed :)

**Comment by katubug** [comment]
Will 1.17.13 be marked compatible with Forge? I currently can't add it to my modpack instance because CF will reject the file as incompatible.

**Comment by MR-CHOO** [comment]
As this was a problem with a much older version, I will be closing this issue.
