### ISSUE TITLE
Add compatibility for Legacy 4J 

### ISSUE THREAD

**Issue by Cixon** [MehVahdJukaar/polytone#42]
Issue Ticket:
https://github.com/Wilyicaro/Legacy-Minecraft/issues/91

Mod:
https://www.curseforge.com/minecraft/mc-mods/legacy-minecraft

**Comment by MehVahdJukaar** [comment]
Not really much I can do. They are using unsafe mixing there, overriding vanilla methods completely instead of using a safe mixin like inject

**Comment by Cixon** [comment]
> Not really much I can do. They are using unsafe mixing there, overriding vanilla methods completely instead of using a safe mixin like inject

gotcha. i appreciate the reply btw! i’ll send this msg over to their discord as a suggestion to see if there’s something that could be done.

**Comment by MehVahdJukaar** [comment]
if you want you can remove some of popytone or that mod mixin from the mixin config json file (invetory mixin) but that will get rid of features
