### ISSUE TITLE
Entire world flickering upon loading

### ISSUE THREAD

**Issue by BlindTwig** [MehVahdJukaar/polytone#43]
As the title says, the entire world flickers when loading into it. Amount of time it does this seems to be tied to how long it takes for chunks to finish fully loading in. This only happens with this mod on, and the resource pack I'm using that makes use of it is Golden Days Base. Attached video displays the problem.

https://github.com/MehVahdJukaar/polytone/assets/58229251/2bfc95a3-54c7-4adc-a167-2bc081013444

**Comment by MehVahdJukaar** [comment]
should be fixed
