### ISSUE TITLE
An option to use hex codes for biome colors/colormaps instead of a png

### ISSUE THREAD

**Issue by zndrmn** [MehVahdJukaar/polytone#45]
Basically what's in the title.

**Comment by zndrmn** [comment]
Just realized that Biome Effects does exactly what I want

**Comment by MehVahdJukaar** [comment]
Colormaps can do that too. They have a static mode or something. Don't remmeber the name exactly but that just require a single hex in their json

**Comment by zndrmn** [comment]
Well now I'm having an issue with getting the biome effect to work.
I'm trying to change the color of the plains biome and nothing changes.
I have no idea what I'm doing wrong.
[colormapEdit.zip](https://github.com/MehVahdJukaar/polytone/files/15373568/colormapEdit.zip)

**Comment by MehVahdJukaar** [comment]
that works for me

**Comment by zndrmn** [comment]
Could it be a mod that's causing it not to work?

**Comment by zndrmn** [comment]
okay so it seems like sodium 1.20.4-0.5.8 is causing it to not work which is strange

**Comment by MehVahdJukaar** [comment]
use embeddium

**Comment by zndrmn** [comment]
is this something that has to be fixed on sodium's side?
