### ISSUE TITLE
Can't change grass and foliage colors

### ISSUE THREAD

**Issue by VindSole** [MehVahdJukaar/polytone#46]
Seems like I can't change the above mentioned, neither can data driven colors like cherry grove's. Sky, fog, water and water fog do work.

**Comment by MehVahdJukaar** [comment]
Send your pack. Also be sure you aren't using sodium

**Comment by VindSole** [comment]
I’m using sodium, didn’t know there were conflicts with it.

**Comment by MehVahdJukaar** [comment]
Use embeddium

**Comment by VindSole** [comment]
Just tried again with embeddium and it still doesn't seem to work, here is the resource pack i'm testing this on.
[https://drive.google.com/file/d/1Ev6AglJDRAEt32MkEa4ezGpqpT3z_JnP/view?usp=sharing](url)

**Comment by MehVahdJukaar** [comment]
that link you sent is private. Also are you sure about this? out of all colors that can be changed foliage and grass are the only 2 that dont need an extra mod for it as vanilla already has 2 textures for their colormaps

**Comment by MehVahdJukaar** [comment]
So ill test that. However if you want to have all those colors in a single file you could use a colormap with grid format instead, using a custom biome_id_mapper to assing each pixel a biome

**Comment by MehVahdJukaar** [comment]
Also i need to know which version you are using

**Comment by MehVahdJukaar** [comment]
Ok I can confirm this issue. I thought that embeddium  was not affected by it but aparently it too doesnt look at those colors. I'll contact the author and see what can be done. This means that the colors wont work with embeddium or sodium but might with a future update of embeddium

**Comment by MehVahdJukaar** [comment]
Actually are you sure you tried with the very latest version of embeddium? this is supposed to not be an issue with that very version

**Comment by VindSole** [comment]
Tried the grid format with sodium, buggy as hell, will try with embeddium,

Using 1.20.6, embeddium 0.3.19, polytone 1.18.11, I'm on the latest version.

**Comment by MehVahdJukaar** [comment]
elaborate on buggy as hell. I worked today with 2 other people both using it with sodium. Also tested it myself today too with embeddium that time.
Question above refers to the biome modifiers. Sodium completely ignores those vanilla objects. Embeddium 0.3.19 is supposed to work ok with them

**Comment by VindSole** [comment]
Blocks start rendering with random textures on sodium
That's odd, tried a grid water colormap and it doesn't look correctly on embeddium either.

**Comment by VindSole** [comment]
tried with a fresh instance with only embeddium and polytone.

**Comment by MehVahdJukaar** [comment]
send your pack so i can test

**Comment by VindSole** [comment]
[Bedrock water colors V1.1.zip](https://github.com/MehVahdJukaar/polytone/files/15440895/Bedrock.water.colors.V1.1.zip)

**Comment by MehVahdJukaar** [comment]
that pack you send works fine for me.
Other one tho had some issues and there was indeed a problem with embeddium compat. Quite a nightmare as forge+ embeddium + fabric all require very different aproaches so mine had to squeezebetween all of them. Anyways new version of the mod should work. Also has many new features

**Comment by VindSole** [comment]
Works fine now, for embeddium at least.
