### ISSUE TITLE
[Bug/Wiki] GUI Overlay not rendering texture.

### ISSUE THREAD

**Issue by RedRain0o0** [MehVahdJukaar/polytone#48]
im trying to make a resource pack using polytone to create a custom ui overlay. problem is i cannot get textures to render no matter what. 
![image](https://github.com/MehVahdJukaar/polytone/assets/96890698/ae265888-8373-4c2a-a7c4-98241e57b2bb)
this is meant to look like this
![creative](https://github.com/MehVahdJukaar/polytone/assets/96890698/682a2140-8c13-47ae-8830-39e315eddf7b)
[legacy_creative.json](https://github.com/user-attachments/files/15539069/legacy_creative.json)
this is my json.
i am on 1.20.6 fabric with polytone 1.18.12
i cant tell if this is an actual bug or unclear documentation (the wiki page contradicts itself several times)

**Comment by MehVahdJukaar** [comment]
so looks like the texture path is wrong. Can you show me where its located?

**Comment by lxly9** [comment]
im also interested, where the wiki contradicts itself. 
as it seems now you have a wrong path to your texture. your texture can be located anywhere, just remember that you’ll need to append .png in the path on newer versions of mc.
it would also greatly help if you could show me your gui_modifier file because we cannot debug without context.

**Comment by lxly9** [comment]
please comment your path to the texture in your folders

**Comment by lxly9** [comment]
if you are using a vanilla-like directory you probably have a container folder in which creative.png is located

**Comment by RedRain0o0** [comment]
sorry, i dont have notifications turned on
in my json i target `assets/halo/textures/gui/creative.png`
im my pack i have `assets/halo/textures/gui/creative.png`
afaik it should work, but it just displays a missing texture no matter what

**Comment by RedRain0o0** [comment]
as for the wiki, at the top of  it says the following is a valid path
```"sprites": [
    {  
      "x": -8,  
      "y": -8,  
      "z": -500,  
      "width": 16,  
      "height": 16,  
      "texture": "textures/block/stone.png"  
    }  
  ]```
but by the bottom it says this is
```"sprites": [  
      {  
        "x": -102,  
        "y": -95,  
        "z": -200,  
        "width": 204,  
        "height": 190,  
        "texture": "assets/modid/textures/gui/container/inventory_frame.png"  
      }  
    ]```
the first doesnt define itself as under `assets/minecraft/` and also doesnt work when put into a pack. everything else works (slots colors, etc), but the stone block doesnt render

**Comment by MehVahdJukaar** [comment]
so all assets in game never have the "assets" folder in their path. its always implied. 
I tested this with this on latest 1.20.1 and it was working for me 
![image](https://github.com/MehVahdJukaar/polytone/assets/24719182/8f027612-495e-4226-9222-40aa64d9c0fc)

**Comment by RedRain0o0** [comment]
does it work on 1.20.6 for you? or is it still broken?

**Comment by MehVahdJukaar** [comment]
ah you are on 1.20.6. There all sprites have to be in the gui/sprites folder. Check the wiki again

**Comment by RedRain0o0** [comment]
tried putting it under `halo/textures/gui/sprites` and `minecraft/textures/gui/sprites` and neither work. also the wiki doesnt seem to mention anything about it

**Comment by MehVahdJukaar** [comment]
![image](https://github.com/MehVahdJukaar/polytone/assets/24719182/643c3fa5-00c7-49d4-99c7-b6b683f602e7)
