### ISSUE TITLE
Polytone can't change custom text color

### ISSUE THREAD

**Issue by Akoto090** [MehVahdJukaar/polytone#49]
Hey, Im currently using [polytone-1.20-1.20.1.jar](https://www.curseforge.com/minecraft/mc-mods/polytone/files/5397381) for Neoforge and want to use the custom text color feature.

My resourcepack does have the [colors.json](https://github.com/user-attachments/files/15570426/colors.json) file in this direction: CustomPack/assets/minecraft/polytone/colors.json
I tried to use the "text" modifer which is also used on the [wiki](https://www.curseforge.com/minecraft/mc-mods/polytone/files/5397381).

While I've successfully changed the color of the xpbar, I'm unable to change the normal text color for other elements like the chat. I've tried both the "code.0" example and the standard "gold" modifier, but neither seems to affect the text color.

For further information, here's my [latest.log](https://github.com/user-attachments/files/15570290/latest.log).
And btw thank you for creating this mod and for your dedication to Polytone!

[colors.json](https://github.com/user-attachments/files/15570426/colors.json)
[latest.log](https://github.com/user-attachments/files/15570290/latest.log)
![image](https://github.com/MehVahdJukaar/polytone/assets/101405799/e8985cbd-3388-4a9e-8c87-501848373362)

**Comment by MehVahdJukaar** [comment]
can you show the file you have?

**Comment by Akoto090** [comment]
```json
{
  "text": {
    "xpbar": "#ffffff",
    "code": {
      "0": "#000000"
    },
    "gold": "#ffffff"
  }
}
```
[Download](https://cdn.discordapp.com/attachments/1066500804430794782/1247675783887982633/colors.json?ex=6660e41f&is=665f929f&hm=ef9b6faa7a73c2b76dff4a578d40c3e959aea60d52efcc3b6a748e5d01d75b7e&)

**Comment by Akoto090** [comment]
It is now fixed! Thank you so much
