### ISSUE TITLE
custom lightmaps?

### ISSUE THREAD

**Issue by glittermutt** [MehVahdJukaar/polytone#5]
would that be possible? please :3

**Comment by MehVahdJukaar** [comment]
yes i know im alraedy wroking on it

**Comment by glittermutt** [comment]
sickkk, thank you!!!

**Comment by glittermutt** [comment]
thank u so much for implementing them!!! how do i get them to work though? ;u;
this is my current setup and it doesnt seem to work
![image](https://github.com/MehVahdJukaar/polytone/assets/134949309/0019e70e-42e9-44d2-a5cd-9728e32f7d3b)

**Comment by MehVahdJukaar** [comment]
Its written on the wiki. They need to be in different paths with diff names. I'll add some backwards compat but that worls0 world-1 name convention was terrible and I'm trying to make something better here

**Comment by glittermutt** [comment]
neither of these work too :( also, on the wiki you have a "here shown below" thingy but theres actually nothing there
![image](https://github.com/MehVahdJukaar/polytone/assets/134949309/dc43fa93-2874-4e71-9e27-4a82a6e92a37)
![image](https://github.com/MehVahdJukaar/polytone/assets/134949309/95b47b97-f65b-4940-b08e-63651ce5bb38)

**Comment by MehVahdJukaar** [comment]
yeah im still working on the lightmap page. Can you send me your pack? All that you have looks about right. Also i addeed support for optifine name shcme aswell for backwards compat

**Comment by MehVahdJukaar** [comment]
oh awesome!
