### ISSUE TITLE
[Fabric/CurseForge] Launcher crash in 1.20.2

### ISSUE THREAD

**Issue by Mat1212fr** [MehVahdJukaar/polytone#50]
Try to make it simple, I want the Fullbright-UB texture-pack working with Sodium, and it need Polytone to work.
When I launch my game with the mod disabled, everything is fine (except Fullbright does't load) and when its enable it _simply_ a **launcher crash**.

I download [this file](https://www.curseforge.com/minecraft/mc-mods/polytone/files/5399250) from Jun 5, 2024.

Here my [launcher_log.txt ](https://github.com/user-attachments/files/15749722/launcher_log.txt) (%USERPROFILE%\curseforge\minecraft\Install\laucher_log.txt)

Here my texture packs:
![image](https://github.com/MehVahdJukaar/polytone/assets/99351856/30ebc32c-5518-4553-9c17-46fa9e890a1a)

(My mods are in the laucher_log file).

If you could help me ^^

**Comment by MehVahdJukaar** [comment]
that file is not marked as 1.20.2

**Comment by Mat1212fr** [comment]
Huum, maybe I'm wrong but it seems to be in the name 
![image](https://github.com/MehVahdJukaar/polytone/assets/99351856/5f590c1d-4b18-4033-b034-339aa9db70de)

**Comment by MehVahdJukaar** [comment]
That's the version name

**Comment by Mat1212fr** [comment]
Okay? So if I understand there is not and never will be version for 1.20.2?

**Comment by MehVahdJukaar** [comment]
correct

**Comment by Mat1212fr** [comment]
Thanks
