### ISSUE TITLE
Using multiple resource packs with modifiers leads to not load anything

### ISSUE THREAD

**Issue by ItsRodrigoAl** [MehVahdJukaar/polytone#52]
I have an resource pack which changes the water color of each biome with the format \assets\minecraft\polytone\biome_effects\[The biome].json, and inside of it is coded like this:
{
   "water_color": 5144449,
   "water_fog_color": 5144449
}

Now, I tried to create my own resource adding particles for the plains biome just a test, so I added the template found on https://github.com/MehVahdJukaar/polytone/wiki/Biome-Effect-Modifiers
{
   "fog_color": 2324,
   "water_fog_color": 0,
   "sky_color": 33,
   "particle": {
      "options": {
         "type": "minecraft:poof"
      },
      "probability": 0.2
    }
}

I added this resource pack above the water colored resource pack, and it made my game stop loading, so I restarted it and again it didn't even loaded. I had to fully remove my modifier and it finally loaded again, and I tried maybe deleting some of the biome modifiers and just using the particle one but that didn't work either, meaning that if someone want to use my resource pack with another one, both using Polytone, it wont work

**Comment by MehVahdJukaar** [comment]
i need latest.log,
Also adding multiple modifiers targeting the same biome will have them be merged. order depends on file name. ovciously its not something that should be done i they have overlapping attributes

**Comment by MehVahdJukaar** [comment]
also try the one in the sample pack. thos i know work. the one on the wiki could have some typos

**Comment by ItsRodrigoAl** [comment]
There's no typo. I mean, using only the template from https://github.com/MehVahdJukaar/polytone/wiki/Biome-Effect-Modifiers works, or using only the biome water change work, but using both at same time from different resource packs is the problem, It doesn't even need to override something because the water one only changes the water color/fog depending on the biome, and on the template it just changes the end particles

Update: the issue with the non-reloading or even the non-loading issue is because I have another mod that changes how the game loads. However, on this log I only used Fabric and Polytone, and it basically unloads both resource packs If I use them both at same time, so yeah Polytone is having issues with that

[latest.log](https://github.com/user-attachments/files/15816744/latest.log)

**Comment by MehVahdJukaar** [comment]
it says you have 2 files with ID minecraft:deep_dark. You can oly have one with that name. that doesnt mean however you cant target that biome with multiple files

**Comment by MehVahdJukaar** [comment]
note ill change it so in newer version it will not throw an error but a warning saying the same thing, that 1 of those files was ignored

**Comment by ItsRodrigoAl** [comment]
Ohhh, wait, I think all of this was only a misunderstood. See, I don't have two same textures or files:

From the water color texture pack, it uses `\assets\minecraft\polytone\biome_effects\deep_dark.json` to only change the water and water fog colors

From my texture pack, it uses `\assets\minecraft\polytone\biome_modifiers\deep_dark.json` to only add particles to that biome

As you can see, both uses different directories, **however** I have no idea why the author of that water texture pack named the folder "biome_effects" instead of "biome_modifiers". Now I changed the name of both to be "biome_modifiers" and I have no problems now, it loads and unloads just fine, so was a problem with the folder naming thing. However, a fix for this problem of having a wrong folder and using two different texture packs should be made yeah

**Comment by MehVahdJukaar** [comment]
biome_effects is the legacy name of biome_modifiers. It still works for compatibility reason but the new correct folder is "biome_modifiers"
I'll remove the old convention in a new update. this was done so all polytone stuff that changes things ends with _modifiers
