### ISSUE TITLE
1.21 version

### ISSUE THREAD

**Issue by CommandGenius** [MehVahdJukaar/polytone#53]
This mod is very useful for texture packs, and a 1.21 version would set it up for the future of resource packs on 1.21.

**Comment by MehVahdJukaar** [comment]
you people need to learn to have patience. 1.21 literally came out yesterday

**Comment by CommandGenius** [comment]
> you people need to learn to have patience. 1.21 literally came out yesterday

i'm only doing this to get the first spot, sorry if i annoyed you.
