### ISSUE TITLE
Fog colors are incorrect when using resource packs with OptiFine fog colormaps

### ISSUE THREAD

**Issue by REMDRIFT** [MehVahdJukaar/polytone#54]
Polytone makes fog colors darker than they should be when using resource packs that have OptiFine fog colormaps.

The two versions I looked at where this occurs are 1.20.6-2.0.2 (Fabric) and 1.20-2.0.4 (Fabric). Here is a link to one of the packs where this occurs: https://github.com/PoeticRainbow/golden-days (the version of the pack I used is "Golden Days Base")

Here is a comparison between OptiFine and Polytone (no other mods included):
![opt_v_poly](https://github.com/MehVahdJukaar/polytone/assets/161157697/b8977c0e-d337-4d97-a281-0f4a26c26e89)

**Comment by MehVahdJukaar** [comment]
that snow block there isa different color tooso something else is at play. Did you have any shader on?
Polytone simply assigns the color value to its biome, there arent any color manipulation done there at all. what the game does with the color is just vanilla logic then after

**Comment by REMDRIFT** [comment]
I took these screenshots in a fresh instance of Minecraft. All settings are at their defaults, and there are no shaders. The only mods used were Optifine, Polytone and Fabric API. I did several tests and I believe this is an issue with Polytone itself.

I noticed that the snow is brighter when using OptiFine; this is unrelated to the issue of fog being incorrect in Polytone. OptiFine makes all terrain slightly brighter than Vanilla/Fabric (I assume it is either a bug or an unintentional side effect caused by one of the mod's optimizations).

Upon closer inspection I also see that the color of the sky slightly differs between OptiFine and Polytone (it is a slightly more vibrant purple in OptiFine). I understand that legacy compat is not the primary scope, but I do not really see the point of it existing if the colors are going to be incorrect. But if you think it is an issue not worth tackling, I understand.

**Comment by REMDRIFT** [comment]
And just to clarify, I am not implying that it is strictly an issue with Polytone, as you said that what the game does with the color is handled by vanilla logic. If that is the case, then the issue is that Polytone does not account for this.

**Comment by MehVahdJukaar** [comment]
Yeah but you know that optfine had a built-in shader that look very much like normal but is a bit different, tent to make things brighter

**Comment by REMDRIFT** [comment]
The built in OptiFine shader (named "internal") was already disabled when I took the screenshots; my shaders are set to "OFF" in the menu. It seems fog is just brighter in OptiFine regardless of the settings. I am quite confident that the fog color in the OptiFine screenshots is how it is intended to look.

Comparison image:
![comparison](https://github.com/MehVahdJukaar/polytone/assets/161157697/7cf29176-96bc-4b02-b2aa-4e929a30c446)

**Comment by MehVahdJukaar** [comment]
so theres not much i can do here. My code replaces the biome sky color lookup that vanilla does with a color picked directly from colormap without any other postprocessing. If optifine happens to do some other obscure thing here theres not much i can do because the mod is close source so I cant look at its code and even if it wasnt i would still not do it as mine would be more correct.
Also

**Comment by REMDRIFT** [comment]
Alright, thank you for your time. I understand if it ends up not being fixed.

**Comment by MehVahdJukaar** [comment]
to add onto this. game by default does something weird with fog color. actual fog color is a blend between fog and sky color. At render distance of 32 its all fog color, at render distance of 4 its all sky color. Sky colo itself has some post processing applied to it (stuff related to sun and time of day, this is where that discrepancy comes from). I didnt look into that yet tho
