### ISSUE TITLE
changing color of turtle master potion

### ISSUE THREAD

**Issue by goldstargloww** [MehVahdJukaar/polytone#56]
i'm not really sure if this counts as an issue, but i don't know where else to put this

how do you change the color of a turtle master potion? i've tried `turtle_master`, but that doesn't work, and i don't know what else to try. is it possible?

**Comment by MehVahdJukaar** [comment]
colors are per effect not per potions. Turtle master uses the color of its 2 effects which are mixed and combined

**Comment by goldstargloww** [comment]
so how would you do it for that?

**Comment by MehVahdJukaar** [comment]
using the custom colors section. Follow the wiki and change the colors of those 2 effects

**Comment by goldstargloww** [comment]
so would the color of the turtle master potion be the color of the two effects combined somehow?

**Comment by MehVahdJukaar** [comment]
Yes. That's how vanilla calculates all potion colors

**Comment by goldstargloww** [comment]
alright cool, thanks, sorry hjkfgrsd
