### ISSUE TITLE
Polytone 1.21 doesn't work at all with NewDefault+

### ISSUE THREAD

**Issue by Haiden47** [MehVahdJukaar/polytone#57]
i  wanted to use FO ( Fabulously Optimized ) modpack on 1.21 , and i get some problems with my texture pack ND+ ( New Default + ) and Polytone seem to be the problem , this is a video of me loading my texture with only Polytone and nothing else
https://github.com/MehVahdJukaar/polytone/assets/90899147/34edaf1f-66c8-455c-af3d-ea992d095247

When i load ND+ with my modpack , the first time i got an error same as the video , but except the game load and if i leave the game with my texture pack loaded , it's just show a black screen forever

**Comment by Haiden47** [comment]
[latest.log](https://github.com/user-attachments/files/15960044/latest.log)

i send the latest log with that

**Comment by MR-CHOO** [comment]
Same answer as #55, is an issue with the packs, and have to be fixed by the pack developers
