### ISSUE TITLE
[1.20.1] [FABRIC] Colored blocks are white with Patrix RP

### ISSUE THREAD

**Issue by EnderGirl1500** [MehVahdJukaar/polytone#59]
It is known that with Patrix RP coloured blocks (wool, terracotta, etc.) are all white in 1.20.1 and below. It needs Colormatic to work. Since Colormatic no longer receives updates, I searched for alternatives and found Polytone. Sadly, it didn't fix the issue. Is there something I can do?

**Comment by MehVahdJukaar** [comment]
polytone does not support colormatic format (for the most part). it would have to be change to use polytone format

**Comment by EnderGirl1500** [comment]
Ohh okay :( is there any way I could do that easily? Tbh I feel lost just by looking at the wiki's home page...

**Comment by MehVahdJukaar** [comment]
theres many ways to do it, you want to look at the block modifiers section. Add a simple modifier with "colormap": "ff00ff" for a static color

**Comment by monoamin** [comment]
Hello, there is a patched version of patrix available within this modpack here that includes the correct block color overrides:
https://modrinth.com/modpack/packtrix

Applied in the correct order:
![grafik](https://github.com/user-attachments/assets/77c22a3c-300d-4a51-a446-ff564329f302)
