### ISSUE TITLE
mod does not have an "External resources" tab on modrinth

### ISSUE THREAD

**Issue by kakashi1464** [MehVahdJukaar/polytone#6]
Polytone: 
![image](https://github.com/MehVahdJukaar/polytone/assets/126709049/201dedb4-db63-4cf4-ae9d-981607408cfb)

Sodium(example of what it should look like):
![image](https://github.com/MehVahdJukaar/polytone/assets/126709049/63a7164e-f2e7-415f-b717-827747c179e6)

**Comment by MehVahdJukaar** [comment]
well thats true but the wiki is still linked there 3 times 💀
