### ISSUE TITLE
[1.21]  The mods 'Polytone' and 'Sodium' are incompatible.

### ISSUE THREAD

**Issue by MetricsLite** [MehVahdJukaar/polytone#61]
https://mclo.gs/t9NJwId#L7

**Comment by MehVahdJukaar** [comment]
I don't see anything related to either mods. All I see is this mixin added field "this.esp$eatPackButton", probably added by a "esp" mod. Also even if there was such an issue since embeddium does work with this, it would have been a sodium issue
