### ISSUE TITLE
[Fabric 1.21] Custom Sound Registry might be broken

### ISSUE THREAD

**Issue by WitheredWasabi** [MehVahdJukaar/polytone#62]
[auzios.zip](https://github.com/user-attachments/files/16167847/auzios.zip)
pack that suffers the issue

"Caused by: java.lang.IllegalStateException: Could not decode Client Block Property with json id minecraft:lime_shulker_box
 error: Unknown registry key in ResourceKey[minecraft:root / minecraft:sound_event]: auzios:sound.shulker_box.step; Unknown registry key in ResourceKey[minecraft:root / minecraft:sound_event]: auzios:sound.shulker_box.hit; Unknown registry key in ResourceKey[minecraft:root / minecraft:sound_event]: auzios:sound.shulker_box.place; Unknown registry key in ResourceKey[minecraft:root / minecraft:sound_event]: auzios:sound.shulker_box.step; Unknown registry key in ResourceKey[minecraft:root / minecraft:sound_event]: auzios:sound.shulker_box.break"

full log [latest.log](https://github.com/user-attachments/files/16167884/latest.log)

**Comment by MehVahdJukaar** [comment]
so i cant replicate this like that. If i reload the pack while ingame custom sounds work. There are however other errors due to newly added neoforge stuff that make it complain about registry sync so those will have to be looked at

**Comment by MR-CHOO** [comment]
This is a bug with your pack, not polytone. Issue closed
