### ISSUE TITLE
Polytone 1.21-2.1.0 crash Neoforge-21.0.95/21.0.91 instanly

### ISSUE THREAD

**Issue by KahnhEl** [MehVahdJukaar/polytone#65]
https://hastebin.com/share/ojiqovomep.bash

**Comment by enduum** [comment]
Same issue I think. No crash report, just latest.log

with NeoForge 21.0.95-beta: https://pastebin.com/jHGcR4aS
with NeoForge 21.0.98-beta (current latest): https://pastebin.com/Ztwj1RS3

**Comment by MehVahdJukaar** [comment]
neo keeps on doing breaking changes so stuff like this will keep on happening for mods until neo is out of beta i will assume
