### ISSUE TITLE
All banners and shield designs become solid white while using a resource pack that changes dye colors

### ISSUE THREAD

**Issue by razorchase49** [MehVahdJukaar/polytone#68]
![2024-07-24_17 14 18](https://github.com/user-attachments/assets/4a431028-e595-4a72-89b9-fb538f097bb9)
![2024-07-24_17 14 28](https://github.com/user-attachments/assets/5213a7b3-4cf6-412b-9a4c-6566d132e3a0)
![2024-07-24_17 14 56](https://github.com/user-attachments/assets/c7b68854-9ac7-4930-a93c-e5f6ac234e5e)
![2024-07-24_17 37 49](https://github.com/user-attachments/assets/ddfd5f97-d40c-4046-a4f3-be737237aadb)
![2024-07-24_17 37 57](https://github.com/user-attachments/assets/179940fa-3af2-4eb8-86bd-418a0fc8031f)

[latest.log](https://github.com/user-attachments/files/16368077/latest.log)

Minecraft version: 1.21
Polytone version: 1.21-2.1.3
Fabric version: 0.16.0

I'm hoping this is self-explanatory, but simply put, when using any resource pack that attempts to change the color values of those you see on banners and shields, all banners and shields appear as blank white banners/shields with no other color or designs visible at all. This happens to all renders of the banners and shields, both as items in the player inventory and as blocks. To replicate, load with Gerudoku Faithful, Golden Days, or any other resource pack that alters dye colors and you'll notice. I've attached screenshots that use an Ominous banner as an example.

Additionally, what baffles me is that the logs (sample attached) does not mention anything to what might be causing this. The closest message I could find is that Polytone has compatibility issues with Sodium, which is irrelevant because this has not been an issue before when playing with Sodium and Polytone simultaneously. I'm wondering if this could be fixed, or at least I could have some light shed on why this issue has suddenly started.

**Comment by MehVahdJukaar** [comment]
hm does this happen on 1.20.1 too?

**Comment by razorchase49** [comment]
No, colors and designs show on 1.20.1. Using same Fabric and Polytone version numbers.
![2024-07-25_08 28 00](https://github.com/user-attachments/assets/6b300ffd-1aab-4a33-917a-bbb4def04944)

**Comment by razorchase49** [comment]
Also, I just now ran the game on 1.21 with Gerodoku Faithful and no mods other than Polytone. The banners and shields are all still blank white. So I can confirm it is not a mod conflict. I've attached the log below.
[latest.log](https://github.com/user-attachments/files/16378484/latest.log)

**Comment by razorchase49** [comment]
As of version 2.1.6, I can confirm that this issue is now fixed? Interesting how the problem was that all the colors had an alpha of 0. Thank you for fixing this.

**Comment by MehVahdJukaar** [comment]
fixed
