### ISSUE TITLE
Colormaps based on biome ID which use a biome ID mapper with a "texture_size" property map colors incorrectly starting from biome 17 

### ISSUE THREAD

**Issue by gaboscharff99** [MehVahdJukaar/polytone#69]
**Version:** v1.21-2.2.5

I have the following files under `/assets/minecraft/polytone` in my custom resource pack:

- `/block_modifiers/nature.json`:
```json
{
    "targets": [
        "grass_block",
        "short_grass",
        "tall_grass",
        "fern",
        "large_fern",
        "potted_fern",
        "oak_leaves",
        "jungle_leaves",
        "acacia_leaves",
        "dark_oak_leaves",
        "mangrove_leaves",
        "vines",
        "birch_leaves",
        "spruce_leaves"
    ],
    "colormap": "nature"
}
```
- `/colormaps/nature.json` (with its corresponding `nature.png`, a 64-pixels-wide, 1-pixel-tall image, in the same location):
```json
{
    "x_axis": "biome_id",
    "y_axis": "0",
    "default_color": 1812487,
    "triangular": false,
    "biome_id_mapper": "biomes"
}
```
- `/biome_id_mappers/biomes.json`:
```json
{
    "plains": 1,
    "sunflower_plains": 2,
    "snowy_plains": 3,
    "ice_spikes": 4,
    "desert": 5,
    "swamp": 6,
    "mangrove_swamp": 7,
    "forest": 8,
    "flower_forest": 9,
    "birch_forest": 10,
    "dark_forest": 11,
    "old_growth_birch_forest": 12,
    "old_growth_pine_taiga": 13,
    "old_growth_spruce_taiga": 14,
    "taiga": 15,
    "snowy_taiga": 16,
    "savanna": 17,
    "savanna_plateau": 18,
    "windswept_hills": 19,
    "windswept_gravelly_hills": 20,
    "windswept_forest": 21,
    "windswept_savanna": 22,
    "jungle": 23,
    "sparse_jungle": 24,
    "bamboo_jungle": 25,
    "badlands": 26,
    "eroded_badlands": 27,
    "wooded_badlands": 28,
    "meadow": 29,
    "cherry_grove": 30,
    "grove": 31,
    "snowy_slopes": 32,
    "frozen_peaks": 33,
    "jagged_peaks": 34,
    "stony_peaks": 35,
    "river": 36,
    "frozen_river": 37,
    "beach": 38,
    "snowy_beach": 39,
    "stony_shore": 40,
    "warm_ocean": 41,
    "lukewarm_ocean": 42,
    "deep_lukewarm_ocean": 43,
    "ocean": 44,
    "deep_ocean": 45,
    "cold_ocean": 46,
    "deep_cold_ocean": 47,
    "frozen_ocean": 48,
    "deep_frozen_ocean": 49,
    "mushroom_fields": 50,
    "dripstone_caves": 51,
    "lush_caves": 52,
    "deep_dark": 53,
    "nether_wastes": 54,
    "warped_forest": 55,
    "crimson_forest": 56,
    "soul_sand_valley": 57,
    "basalt_deltas": 58,
    "the_end": 59,
    "end_highlands": 60,
    "end_midlands": 61,
    "small_end_islands": 62,
    "end_barrens": 63,
    "texture_size": 64
}
```

However, after extensive testing of this colormap, even with different images with the same dimensions but different colors, I've concluded that only the undefined biomes (which map to 0) and biomes mapped to any number between 1-16 actually take the correct colors from the colormap. Biomes numbered 17 and onwards do not, and instead take the color for the next biome defined in the mapper (so biome 17 takes the color for biome 18, 18 for 19, and so on). In this example, the savanna biome would take the color meant to be used for the savanna plateau, and the savanna plateau would take the color for windswept hills, while the windswept hills would take the one for windswept gravelly hills, and so on. After thoroughly checking the wiki and my own files for mistakes multiple times, I cannot think of any possibilty for why this happens other than a bug.

It should be noted that I have not tested this with images of different sizes, or without using the `texture_size` property. It should also be noted that the prebuilt `grid` colormap without a biome ID mapper works as intended, for some strange reason. Perhaps it doesn't use the `texture_size` property if no biome ID mapper is used?

**Comment by MehVahdJukaar** [comment]
can you send the pack you are using or that relevant part, texture included?

**Comment by gaboscharff99** [comment]
[Chaos Visuals.zip](https://github.com/user-attachments/files/16402061/Chaos.Visuals.zip)
A lot of textures are missing since this is a pretty early WIP.

**Comment by MehVahdJukaar** [comment]
So i cant replicate. I tried changing the plains pixel to yellow as such and this is what I got
![image](https://github.com/user-attachments/assets/ab2db833-ac05-4288-bb86-7622c0bac457)
![image](https://github.com/user-attachments/assets/3a9da20d-d713-4671-8ea1-f66fb9fce310)

**Comment by MehVahdJukaar** [comment]
tested in 1.21 latest

**Comment by gaboscharff99** [comment]
As I said, this only happens with biomes number 17 and onwards in the biome ID mapper. It wouldn't happen with the plains biome, because it's number 1.

**Comment by MehVahdJukaar** [comment]
i misted i thought you meant the other way around

**Comment by gaboscharff99** [comment]
Sorry, misunderstanding. But please let me know about your findings.

**Comment by MehVahdJukaar** [comment]
was due to a rounding error. Should be fixed

**Comment by gaboscharff99** [comment]
It's fixed now! Thanks for looking into it!
