### ISSUE TITLE
[FABRIC] crash with sodium and indium

### ISSUE THREAD

**Issue by glittermutt** [MehVahdJukaar/polytone#7]
:(
crash report and log attached, i teleported to a stronghold and the game seemed to crash
https://mclo.gs/hbCYPxM
https://mclo.gs/ZrFvqpb

**Comment by MehVahdJukaar** [comment]
Oh noe

**Comment by MehVahdJukaar** [comment]
Omg why does sodium completely disregards vanilla biome colours providers. Seems like I have to add direct integration with it

**Comment by MehVahdJukaar** [comment]
omg and they made it an enum with no regard whatsoever to mods that miding add some of those and no way to extend it other than going nuclear with a super complicaated core mod i dont even know how to do

**Comment by MehVahdJukaar** [comment]
oh would you look at that theres a PR on sodium exactly for this. too bad its still not being merged for 3 weeks https://github.com/CaffeineMC/sodium-fabric/pull/2222

**Comment by MehVahdJukaar** [comment]
I'll disable colormaps for now. polytone has no way of getting them to work without this. This is completely their issue for not only replacing vanilla system without inheriting from it as it should but also keeping it extremely locked up and non expandable with that enum. My hands are tied until that PR is merged

**Comment by glittermutt** [comment]
i hope it gets merged 😭

**Comment by glittermutt** [comment]
i updated polytone to the latest version, but it still crashed ^^; crash report and log attached
https://mclo.gs/jC3vVYT
https://mclo.gs/FSrd1on

**Comment by Uranite** [comment]
Sodium 0.5.6 is out! 🎉

**Comment by glittermutt** [comment]
hey, is sodium 0.5.6 going to be only for 1.20.3+ only?

**Comment by glittermutt** [comment]
NEVERMIND IM A CRETIN
