### ISSUE TITLE
Separate Transforms Model on Fabric doesn't work on 2.2.2 onwards

### ISSUE THREAD

**Issue by VindSole** [MehVahdJukaar/polytone#70]
Polytone 2.2.2 onwards makes items I'm using this function on to be invisible, wiki and changelog doesn't seem to have changed how to add them, and 2.2.1 works correctly.

**Comment by MehVahdJukaar** [comment]
name might have chaneged to neofroge namespace to match the one on neoforge

**Comment by VindSole** [comment]
That fixed it. thanks.

**Comment by VindSole** [comment]
Should mention this in the wiki
