### ISSUE TITLE
Custom block sounds cause resource reload to fail as of 1.21-2.1.6

### ISSUE THREAD

**Issue by pkfortis** [MehVahdJukaar/polytone#73]
When I try to load my custom sounds resource pack in 1.21-2.1.6 or later, the resource reload fails. In 1.21-2.1.5 and lower it loads and works flawlessly. As far as I can tell from the documentation, the methods for registering custom sound events and customizing block sounds hasn't changed, so I don't know what's up.

All the logs are from Fabric, but based on my quick tests, it looks like this happens in NeoForge as well. I didn't have anything installed other than Polytone and Fabric API.

Polytone.log: 
[polytone.log](https://github.com/user-attachments/files/16419097/polytone.log)

Latest.log:
[latest.log](https://github.com/user-attachments/files/16419098/latest.log)

Pack:
[zip download](https://zantetsuken.com/minecraft/%5b1.20.2+%5d%20A%20Sound%20Improvement.zip) (Sorry, I know it's big, but removing all the custom music and other sounds.json changes proved to be too much of a pain in the ass).

I do want to note that I did try moving all the custom sounds to a unique namespace and it didn't make a difference; I still got the same "Not a JSON object" errors in polytone.log.

**Comment by MehVahdJukaar** [comment]
fixed
