### ISSUE TITLE
[Feature] adding sound_emitters and sound_type overhaul

### ISSUE THREAD

**Issue by LysiBee** [MehVahdJukaar/polytone#74]
Polytone has `sound_type` to change the sounds of a block, i want to suggest adding` sound_emitters` to make it play a sound based on some conditions , similar to `particle_emitters` but with sound (can be seen in vanilla near campfier, etc)

Then maybe also overhaul a `sound_type` to accept conditions? (biome, blockstate, etc) 
That way block could have different sounds\textures\particles based on biomes (and other conditions) with other features of Polytone combined

**Comment by MehVahdJukaar** [comment]
added
