### ISSUE TITLE
[Feature] RAIN colormap expression change

### ISSUE THREAD

**Issue by mineland-2048** [MehVahdJukaar/polytone#77]
i was trying to add a color map that uses the rain and thunder to change colors since i saw in a recent update it was able to do that and found out that the RAIN expresion just includes if its raining or not, and it cant differentiate between rain and thunderstorm.

I would like it if it could be either changed to have it output 0.5 when it is raining normally and 1 when it is in a thunderstorm, or add another PRECIPITATION property to keep compatibility if any packs had been made with that already.

example, this debug colormap goes from 0 to 1 with no inbetween, when id like it to stop at the middle for more control over how it looks
![debug2](https://github.com/user-attachments/assets/2b183499-088a-4a4a-9883-1070ed323a19)

https://github.com/user-attachments/assets/9334f014-dac1-4e06-8eaf-ba131e98c5ef

**Comment by MehVahdJukaar** [comment]
New version is 0.5 rain and 1 for thunder

**Comment by mineland-2048** [comment]
It works now really well now. 
I have another feature idea specifically for these sky color changes on weather, to have a toggle to disable the forced darkness that gets added into the final color, maybe as a property inside a dimension or biome modifier like `"sky_weather_color": false` or something . Dont know if i should make another issue or just leave it here, but it would be really useful for absolute control over how one would want it to look if they choose to toggle it

**Comment by MehVahdJukaar** [comment]
There shouldn't be any force darkness. I mean maybe the lightmap could get darker but that's a different topic

**Comment by mineland-2048** [comment]
Its visible in the video. The debug lightmap has no brightness changes, but rain and thunder make the final color darker by default, due to a bit on the client level renderer code. it checks for the rain level and the thunder level and does some stuff to it, right in the getSkyColor() method of the ClientLevel in mojmap

**Comment by MehVahdJukaar** [comment]
Oh for rainy weather you mean. I see what I can do

**Comment by MehVahdJukaar** [comment]
added
