### ISSUE TITLE
Feature request: Nbt/Components support in Creative Tab Modifiers

### ISSUE THREAD

**Issue by magmamir** [MehVahdJukaar/polytone#80]
If it wouldn't be too hard to implement, it would be very nice to have an opportunity to add items with predefined components in creative tabs menu with resource pack, in a similar way like for example [MoreCreativeTabs](https://modrinth.com/mod/morecreativetabs) mod did that. It would be very useful for both — datapack creators who will be able to add custom items in a very convenient way for players in creative, and average players who can add important for them items (like swords with enchantments or chests with items) to one of the tabs for quick access.

**Comment by MehVahdJukaar** [comment]
you can aleady do that. creative tab modifiers can add ItemStacks

**Comment by magmamir** [comment]
Oh, my bad. I didn't see section about Item Stack
