### ISSUE TITLE
Colormapped blocks remain white in invetory

### ISSUE THREAD

**Issue by CloverCorp** [MehVahdJukaar/polytone#90]
Running a pack with polytone in it while i update my personal texture pack and i noticed that blocks that would normally retain the default color while in inventory (grass block and most leaves) turn white rather than maintain their default color.

mod version: polytone-1.21-2.4.12-fabric.jar
running the vital modpack with extremely minor changes (mod updates for sodium, its dependancies and EMF/ETF)
another note this is using the optifine format for cross compat between the two.
![image](https://github.com/user-attachments/assets/31fa06de-3fb9-44dc-8b7c-612f77bc2ce2)

**Comment by MehVahdJukaar** [comment]
Did you add an item colormap? Blocks and items are two different things

**Comment by CloverCorp** [comment]
How would i format that, im rather new to polytone.

**Comment by MehVahdJukaar** [comment]
written on the wiki, item modifier section.
