### ISSUE TITLE
Incompatible with Sodium 0.5.11

### ISSUE THREAD

**Issue by Kitt2k4** [MehVahdJukaar/polytone#91]
I tried to download this mod in order to use Shrimp's Distonct Potion Resource pack, but I got noticed that this mod is incompatible with Sodium version 0.5.11 and earlier

**Comment by MehVahdJukaar** [comment]
yes exactly what that says. you need newer sodium, needed for its many bug fixes

**Comment by Psychodeus** [comment]
@MehVahdJukaar But the other version of Sodium is in Beta.

**Comment by MehVahdJukaar** [comment]
And?
Closing this as whichever way you look at it it's not my issue
