### ISSUE TITLE
1.20.1 Biome Fog Shape Breaks with Blindness Effect and Ender Dragon Boss Fight Fog

### ISSUE THREAD

**Issue by FusionSwarly** [MehVahdJukaar/polytone#98]
It seems fog start value is affected by the blindness effect, which will make fog much denser than desired. Same goes for the fog during the ender dragon fight.

Biome fog shapes from polytone resource packs should be overridden by these effects, so that they dont completely obscure the screen.

To replicate, simply use a resource pack that changes fog start to a larger size (around 10) and give yourself the blindness effect. This will make the blindness effect turn the entire screen black due to the dense fog.
![image](https://github.com/user-attachments/assets/70557ac1-ecbd-41d6-8fc4-3d783e61620b)

Tested in 1.20.1 Forge

**Comment by MehVahdJukaar** [comment]
Well the way that I made this is that it's a scalar applied to whatever the fog start currently is (as it can depend on many things such as view distance and as you say the blindness effect). So essentially if the for is low there with blindness will be even lower

**Comment by FusionSwarly** [comment]
This effect is undesirable for most use cases, so I think the default behavior should be disabling biome fog effects when these effects are active, or at least add a way to detect if fog is being affected by something like blindness or the ender dragon.
